Added contact, about, footer
utkarsh2102/linuxchixin pull request #13
Opened 2018-11-10 10:42 UTC by avinashkr1612

Solved #11 #9 #6

2018-11-10 10:52 UTC, shivan1b commented
You need to clean your git history. There should not be any "Merged bla bla with my branch" commits. Rebase and push only your changes properly.
And, please create a separate branch with a meaningful name. `master` should be your main branch, you should keep it even with the upstream.

2018-11-10 15:14 UTC, utkarsh2102 requested changes
Hey,
- Comments inline.
- Besides that, you need to create different branches for different issues.
- We do not accept PRs having more than 1 logical change or having more than 1 commit. Hence, requesting you to please squash commits and open 3 different PRs.
- Also, write a good commit message. Having a clean history as @shivan1b said, is really important.

Although we are thankful for the contribution, we cannot accept PRs like that.
Just make the requested changes and then you're good to go.

2018-11-10 15:14 UTC, utkarsh2102 commented on _config.yml
> +baseurl: "" # the subpath of your site, e.g. /blog
This will not render the styling.
Please add this back.

2018-11-10 15:14 UTC, utkarsh2102 commented on _includes/footer.html
> +<footer class="c-footer" style="background:#673AB7;color:#fff;" >
Please add appropriate space b/w them so as to adhere to the styling guide.

2018-12-10 04:09 UTC, utkarsh2102 commented
Hey,
We have changed the outlook of the website.
Please feel free to contact me if you still like to contribute.

2018-12-10 04:09 UTC, closed without merging